import "~/styles/globals.css";
import "@mantine/core/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/nprogress/styles.css";

import React from "react";

import {ColorSchemeScript, createTheme, MantineProvider} from "@mantine/core";
// eslint-disable-next-line import/no-unresolved
import {GeistSans} from "geist/font/sans";

import {TRPCReactProvider} from "~/trpc/react";

import type {Metadata} from "next";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const theme = createTheme({});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <MantineProvider theme={theme}>
            {children}
          </MantineProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
